import os
import sys
import json
import asyncio
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent
PYTHON_EXE = sys.executable

def print_header(title):
    print("\n" + "=" * 60)
    print(f"  {title}")
    print("=" * 60)

def setup_env():
    print_header("Step 1: Discord Bot Credentials")
    env_file = REPO_ROOT / ".env"
    
    current_token = ""
    current_channel = ""
    current_mention = ""

    if env_file.exists():
        print("Existing .env file detected.")
        for line in env_file.read_text(encoding="utf-8").splitlines():
            if line.startswith("DISCORD_BOT_TOKEN="):
                current_token = line.split("=", 1)[1].strip()
            elif line.startswith("DISCORD_CHANNEL_ID="):
                current_channel = line.split("=", 1)[1].strip()
            elif line.startswith("DISCORD_MENTION_ROLE_OR_USER="):
                current_mention = line.split("=", 1)[1].strip()

    prompt_token = input(f"Discord Bot Token [{current_token[:6]}...]: ").strip()
    bot_token = prompt_token if prompt_token else current_token

    prompt_channel = input(f"Discord Channel ID [{current_channel}]: ").strip()
    channel_id = prompt_channel if prompt_channel else current_channel

    prompt_mention = input(f"Optional Mention/Role ID (e.g. <@123456789>) [{current_mention}]: ").strip()
    mention = prompt_mention if prompt_mention else current_mention

    if not bot_token or not channel_id:
        print("❌ Error: Bot Token and Channel ID are required.")
        sys.exit(1)

    env_content = f"""# Auto-generated by install.py
DISCORD_BOT_TOKEN={bot_token}
DISCORD_CHANNEL_ID={channel_id}
LOCAL_PORT=9876
TIMEOUT_SECONDS=300
DISCORD_MENTION_ROLE_OR_USER={mention}
"""
    env_file.write_text(env_content, encoding="utf-8")
    print("✅ Saved configuration to .env")
    return bot_token, channel_id

async def verify_discord(token: str, channel_id: int):
    print_header("Step 2: Testing Discord Connection")
    import discord
    intents = discord.Intents.default()
    client = discord.Client(intents=intents)

    success = False
    try:
        @client.event
        async def on_ready():
            nonlocal success
            print(f"✅ Logged in as: {client.user}")
            channel = client.get_channel(channel_id)
            if channel:
                embed = discord.Embed(
                    title="🚀 Discord Agent Gate Connected!",
                    description="Discord Agent Gate is successfully configured and ready to handle AI agent confirmations.",
                    color=0x57F287
                )
                embed.add_field(name="Status", value="🟢 Online & Listening", inline=True)
                embed.add_field(name="Target Channel", value=f"#{channel.name}", inline=True)
                embed.set_footer(text="Made by github.com/moddatei • Discord Agent Gate")
                embed.set_author(name="Discord Agent Gate", url="https://github.com/moddatei/discord-agent-gate")
                await channel.send(embed=embed)
                print(f"✅ Sent test embed to channel #{channel.name} ({channel_id})")
                success = True
            else:
                print(f"⚠️ Warning: Could not find channel {channel_id}. Verify bot has access to that channel.")
            await client.close()

        print("Connecting to Discord...")
        await asyncio.wait_for(client.start(token), timeout=15)
    except Exception as e:
        print(f"❌ Connection test failed: {e}")
    finally:
        if not client.is_closed():
            await client.close()
    return success

def get_runner_cmd(agent: str) -> str:
    client_script = (REPO_ROOT / "client.py").as_posix()
    py_bin = "python" if sys.platform == "win32" else "python3"
    return f'{py_bin} {client_script} --agent {agent}'

def configure_antigravity(matcher: str = "ask_question|run_command"):
    print_header("Configuring Google Antigravity (AGY)")
    cmd_str = get_runner_cmd("antigravity")

    # Global config location for Antigravity: ~/.gemini/config/hooks.json
    global_dir = Path.home() / ".gemini" / "config"
    global_dir.mkdir(parents=True, exist_ok=True)
    hooks_file = global_dir / "hooks.json"

    data = {}
    if hooks_file.exists():
        try:
            data = json.loads(hooks_file.read_text(encoding="utf-8"))
        except Exception:
            data = {}

    data["discord-remote-gate"] = {
        "PreToolUse": [
            {
                "matcher": matcher,
                "hooks": [
                    {
                        "type": "command",
                        "command": cmd_str
                    }
                ]
            }
        ]
    }

    hooks_file.write_text(json.dumps(data, indent=2), encoding="utf-8")
    print(f"✅ Antigravity hooks updated with matcher '{matcher}': {hooks_file}")

def configure_claude_code():
    print_header("Configuring Claude Code")
    cmd_str = get_runner_cmd("claude")

    # Claude settings location: ~/.claude/settings.json
    claude_dir = Path.home() / ".claude"
    claude_dir.mkdir(parents=True, exist_ok=True)
    settings_file = claude_dir / "settings.json"

    data = {}
    if settings_file.exists():
        try:
            data = json.loads(settings_file.read_text(encoding="utf-8"))
        except Exception:
            data = {}

    if "hooks" not in data:
        data["hooks"] = {}

    data["hooks"]["PermissionRequest"] = [
        {
            "matcher": ".*",
            "hooks": [
                {
                    "type": "command",
                    "command": cmd_str
                }
            ]
        }
    ]

    settings_file.write_text(json.dumps(data, indent=2), encoding="utf-8")
    print(f"✅ Claude Code settings updated: {settings_file}")

def main():
    print("\n" + "#" * 60)
    print("      🤖 DISCORD AGENT GATE INSTALLATION WIZARD")
    print("#" * 60)

    token, channel_str = setup_env()
    
    test_conn = input("\nWould you like to test the Discord connection now? (y/n) [y]: ").strip().lower()
    if test_conn in ("", "y", "yes"):
        try:
            asyncio.run(verify_discord(token, int(channel_str)))
        except Exception as e:
            print(f"Test skipped or failed: {e}")

    print_header("Step 3: Select Notification Sensitivity")
    print("1) Questions & Terminal Commands (Recommended: ask_question | run_command)")
    print("2) Questions & Forms Only (ask_question)")
    print("3) Terminal Commands Only (run_command)")
    print("4) Full Guard (All file edits & commands)")
    
    mode_choice = input("Select sensitivity mode [1]: ").strip()
    matchers = {
        "1": "ask_question|run_command",
        "2": "ask_question",
        "3": "run_command",
        "4": "run_command|write_to_file|replace_file_content"
    }
    selected_matcher = matchers.get(mode_choice, "ask_question|run_command")

    print_header("Step 4: Select AI Agents to Auto-Configure")
    print("1) Google Antigravity (AGY)")
    print("2) Claude Code")
    print("3) OpenAI Codex / Custom Agents")
    print("4) All of the above (Antigravity + Claude Code + Codex)")
    print("5) Skip (Manual setup)")
    
    choice = input("Select an option [4]: ").strip()
    if choice in ("1",):
        configure_antigravity(selected_matcher)
    elif choice in ("2",):
        configure_claude_code()
    elif choice in ("3",):
        print("✅ Codex & Custom Agent Helper ready in 'codex_helper.py'.")
    elif choice in ("", "4"):
        configure_antigravity(selected_matcher)
        configure_claude_code()
        print("✅ Codex & Custom Agent Helper ready in 'codex_helper.py'.")
    else:
        print("Skipped agent auto-configuration.")

    print_header("Setup Complete! 🎉")
    print(f"To start the background daemon, run:")
    print(f"  python daemon.py")
    print("\nAny confirmation required by your AI agents will now be sent directly to your Discord channel!")

if __name__ == "__main__":
    main()
