import os
import sys
import json
import asyncio
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent
PYTHON_EXE = sys.executable

def print_header(title):
    print("\n" + "=" * 60)
    print(f"  {title}")
    print("=" * 60)

def setup_env():
    print_header("Step 1: Discord Bot Credentials")
    env_file = REPO_ROOT / ".env"
    
    current_token = ""
    current_channel = ""
    current_mention = ""

    if env_file.exists():
        print("Existing .env file detected.")
        for line in env_file.read_text(encoding="utf-8").splitlines():
            if line.startswith("DISCORD_BOT_TOKEN="):
                current_token = line.split("=", 1)[1].strip()
            elif line.startswith("DISCORD_CHANNEL_ID="):
                current_channel = line.split("=", 1)[1].strip()
            elif line.startswith("DISCORD_MENTION_ROLE_OR_USER="):
                current_mention = line.split("=", 1)[1].strip()

    prompt_token = input(f"Discord Bot Token [{current_token[:6]}...]: ").strip()
    bot_token = prompt_token if prompt_token else current_token

    prompt_channel = input(f"Discord Channel ID [{current_channel}]: ").strip()
    channel_id = prompt_channel if prompt_channel else current_channel

    prompt_mention = input(f"Optional Mention/Role ID (e.g. <@123456789>) [{current_mention}]: ").strip()
    mention = prompt_mention if prompt_mention else current_mention

    if not bot_token or not channel_id:
        print("❌ Error: Bot Token and Channel ID are required.")
        sys.exit(1)

    env_content = f"""# Auto-generated by install.py
DISCORD_BOT_TOKEN={bot_token}
DISCORD_CHANNEL_ID={channel_id}
LOCAL_PORT=9876
TIMEOUT_SECONDS=300
DISCORD_MENTION_ROLE_OR_USER={mention}
"""
    env_file.write_text(env_content, encoding="utf-8")
    print("✅ Saved configuration to .env")
    return bot_token, channel_id

async def verify_discord(token: str, channel_id: int):
    print_header("Step 2: Testing Discord Connection")
    import discord
    intents = discord.Intents.default()
    client = discord.Client(intents=intents)

    success = False
    try:
        @client.event
        async def on_ready():
            nonlocal success
            print(f"✅ Logged in as: {client.user}")
            channel = client.get_channel(channel_id)
            if channel:
                await channel.send("🚀 **Discord Agent Gate is configured and connected!**")
                print(f"✅ Sent test message to channel #{channel.name} ({channel_id})")
                success = True
            else:
                print(f"⚠️ Warning: Could not find channel {channel_id}. Verify bot has access to that channel.")
            await client.close()

        print("Connecting to Discord...")
        await asyncio.wait_for(client.start(token), timeout=15)
    except Exception as e:
        print(f"❌ Connection test failed: {e}")
    finally:
        if not client.is_closed():
            await client.close()
    return success

def configure_antigravity():
    print_header("Configuring Google Antigravity (AGY)")
    client_script = REPO_ROOT / "client.py"
    cmd_str = f'"{PYTHON_EXE}" "{client_script}" --agent antigravity'

    # Global config location for Antigravity: ~/.gemini/config/hooks.json
    global_dir = Path.home() / ".gemini" / "config"
    global_dir.mkdir(parents=True, exist_ok=True)
    hooks_file = global_dir / "hooks.json"

    data = {}
    if hooks_file.exists():
        try:
            data = json.loads(hooks_file.read_text(encoding="utf-8"))
        except Exception:
            data = {}

    data["discord-remote-gate"] = {
        "PreToolUse": [
            {
                "matcher": "run_command|write_to_file|replace_file_content",
                "hooks": [
                    {
                        "type": "command",
                        "command": cmd_str
                    }
                ]
            }
        ]
    }

    hooks_file.write_text(json.dumps(data, indent=2), encoding="utf-8")
    print(f"✅ Antigravity hooks updated: {hooks_file}")

def configure_claude_code():
    print_header("Configuring Claude Code")
    client_script = REPO_ROOT / "client.py"
    cmd_str = f'"{PYTHON_EXE}" "{client_script}" --agent claude'

    # Claude settings location: ~/.claude/settings.json
    claude_dir = Path.home() / ".claude"
    claude_dir.mkdir(parents=True, exist_ok=True)
    settings_file = claude_dir / "settings.json"

    data = {}
    if settings_file.exists():
        try:
            data = json.loads(settings_file.read_text(encoding="utf-8"))
        except Exception:
            data = {}

    if "hooks" not in data:
        data["hooks"] = {}

    data["hooks"]["PermissionRequest"] = [
        {
            "matcher": ".*",
            "hooks": [
                {
                    "type": "command",
                    "command": cmd_str
                }
            ]
        }
    ]

    settings_file.write_text(json.dumps(data, indent=2), encoding="utf-8")
    print(f"✅ Claude Code settings updated: {settings_file}")

def main():
    print("\n" + "#" * 60)
    print("      🤖 DISCORD AGENT GATE INSTALLATION WIZARD")
    print("#" * 60)

    token, channel_str = setup_env()
    
    test_conn = input("\nWould you like to test the Discord connection now? (y/n) [y]: ").strip().lower()
    if test_conn in ("", "y", "yes"):
        try:
            asyncio.run(verify_discord(token, int(channel_str)))
        except Exception as e:
            print(f"Test skipped or failed: {e}")

    print_header("Step 3: Select AI Agents to Auto-Configure")
    print("1) Google Antigravity (AGY)")
    print("2) Claude Code")
    print("3) Both Antigravity and Claude Code")
    print("4) Skip (Manual setup)")
    
    choice = input("Select an option [3]: ").strip()
    if choice in ("1",):
        configure_antigravity()
    elif choice in ("2",):
        configure_claude_code()
    elif choice in ("", "3"):
        configure_antigravity()
        configure_claude_code()
    else:
        print("Skipped agent auto-configuration.")

    print_header("Setup Complete! 🎉")
    print(f"To start the background daemon, run:")
    print(f"  python daemon.py")
    print("\nAny confirmation required by your AI agents will now be sent directly to your Discord channel!")

if __name__ == "__main__":
    main()
